name: Build docs

on:
  push:
    branches: [ main, development ]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: show infos & make build
        run: |
          node -v
          yarn -v
          make -v
          git config --global user.email "admin@groupeffect.de"
          git config --global user.name 'WorkflowUser-$(date)'
          cd webinterface && yarn install
          cd .. && make build
          git status
          git add .
          git commit -m 'auto build - $(date)'
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:${GITHUB_REF} --no-push
          git status
          