name: Build docs

on:
  push:
    branches: [ main, development ]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: show infos
        run: |
          node -v
          # curl -sL https://deb.nodesource.com/setup_16.x -o nodesource_setup.sh
          # bash ./nodesource_setup.sh
          # apt update && apt install nodejs

          