name: Build docs

on:
  push:
    branches: [ main, development ]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: show infos
        run: |
          node -v
          yarn -v
          make -v
          

          